### ISSUE TITLE
Add sample test on Genetic Algo

### ISSUE THREAD

**Issue by huiwang** [TrueLaurel/CodinGame-Scala-Kit#27]

**Comment by Wei-1** [comment]
I will love to write the tests is no one else had already started it.

**Comment by huiwang** [comment]
@Wei-1 Nobody works on it. I tried but didn't find a good problem demo GA.

**Comment by Wei-1** [comment]
I will give it a try then.

**Comment by huiwang** [comment]
@Wei-1 I got one idea for the sample test: coder strike back! We can simplify the test by taking into account only one pod. The objective is to build a racer pod that finishes 3 laps as fast as possible. what do you think?

**Comment by Wei-1** [comment]
@huiwang How about from start-point to a waypoint and then go back?

**Comment by huiwang** [comment]
Yes, we can get started with this scenario. I think of CSB example because there are no constraints on the generated candidate solution. We are free to make any kind of mutation and crossover.

**Comment by Wei-1** [comment]
https://github.com/TrueLaurel/CodinGame-Scala-Kit/pull/49

**Comment by huiwang** [comment]
Thx for the Test!
