### ISSUE TITLE
Bundler does not work for import org.myorg.MyObject._

### ISSUE THREAD

**Issue by tyrcho** [TrueLaurel/CodinGame-Scala-Kit#3]
Just tried the Bundler for the previous challenge.

I have a fix for this issue, but I'd need your code formatter configuration to avoid formatting differences in the patch.

Apart from that, great tool :)

**Comment by huiwang** [comment]
This is a known Issue. I have to configure an organisation in the bundler. It's currently truelaurel.com

I just the default formatter in intellij :)

**Comment by tyrcho** [comment]
I guess I'll use IntelliJ to work on this project then, it'll be easier especially with sbt.

**Comment by huiwang** [comment]
@tyrcho I switched to Intellij three or four years ago and I've never regretted my choice.

**Comment by tyrcho** [comment]
I'm trying :)
https://github.com/tyrcho/idea-settings

Any tips specific to scala ? I have plenty of colleagues who use it but for
Java dev.

Btw, have you seen my MR on Gitlab ?

**Comment by huiwang** [comment]
I don't have any specific settings. The default one is quite good.
Yes, I added some comments.
