### ISSUE TITLE
Better package organisation

### ISSUE THREAD

**Issue by tyrcho** [TrueLaurel/CodinGame-Scala-Kit#35]
@huiwang Can we decide here the package organisation ?

 I think we need to define :

1.  the root, common package for the organisation. Something like scalakit ?
1.  the package for codingame related stuff (bundler, arena, referee ...)
1.  the package for specific ai algorithms (annealing, mcts, alphabeta ...)
1.  maybe a specific package for game samples (gomoku, tictactoe, connect4 ...)

**Comment by tyrcho** [comment]
Proposal

1. org.scalakit
1. org.scalakit.codingame
1. org.scalakit.algoithms
1. org.scalakit.games

**Comment by Wei-1** [comment]
how about:
4. org.scalakit.samplegames
games seems too general

**Comment by huiwang** [comment]
Good idea 👍 !

To continue with your guy's proposals

1. org.scalakit
2. org.scalakit.codingame # codingame architecture GameState, Action, Player, Arenna
3. org.scalakit.algorithms # search, minimax, genetics, mcts..
4. org.scalakit.games?/samplegames?/puzzles? # specific game examples to solve
5. org.scalakit.tools # bundler
6. org.scalakit.math # vectorial, random, numbers
7. org.scalakit.physics # collision
8. org.scalakit.geometry # hexagon

**Comment by tyrcho** [comment]
my next try :)

2. org.scalakit.codingame # codingame architecture GameState, Action, Player, Arena
5. org.scalakit.codingame.tools # bundler
3. org.scalakit.algorithms # search, minimax, genetics, mcts..
4. org.scalakit.samplegames # specific game examples to solve
6. org.scalakit.math # vectorial, random, numbers
8. org.scalakit.math.geometry # hexagon
7. org.scalakit.physics # collision
9. org.scalakit.collection # i think of the Michel's implicts on maxOption, minOption, DataGrid or other useful data strucutres
9. org.scalakit.fp.state # State Monad

root name can be com.truelaurel instead of org.scalakit

**Comment by Wei-1** [comment]
@tyrcho What's the meaning of fp in 9?

**Comment by huiwang** [comment]
It means functional programming
